<?php
$z[0]=Array("global","",62,90);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("global","",158,184);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",238,268);
$z[2][4]['name']="cfg_description";
$z[3]=Array("global","",306,333);
$z[3][4]['name']="cfg_keywords";
$z[4]=Array("global","",1241,1267);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("channel","\n						<li> <a href=\"list.php?tid=[field:id/]\">[field:typename/]</a>\n						</li>",1681,1810);
$z[5][4]['type']="top";
$z[5][4]['row']="10";
$z[6]=Array("mda","",1848,1873);
$z[6][4]['name']="468x60";
$z[7]=Array("arclist","\n				<li>\n					<a href=\"view.php?aid=[field:id/]\">\n						<img src=\"[field:litpic/]\">\n					</a>\n				</li>",2020,2170);
$z[7][4]['flag']="f";
$z[7][4]['row']="5";
$z[8]=Array("arclist","\n					<li class=\"am-g am-list-item-desced am-list-item-thumbed am-list-item-thumb-left\">\n						<div class=\"am-u-sm-4 am-list-thumb\">	<a href=\"[field:arcurl/]\">[field:image/]</a>\n						</div>\n						<div class=\"am-u-sm-8 am-list-main\">\n							 <h3 class=\"am-list-item-hd\"><a href=\"[field:arcurl/]\">[field:title/]</a></h3>\n							<div class=\"am-list-item-text\">[field:description/]</div>\n						</div>\n					</li>",2461,2966);
$z[8][4]['row']="10";
$z[8][4]['orderby']="pubdate";
$z[8][4]['type']="image.";
$z[8][4]['imgwidth']="150";
$z[8][4]['imgheight']="150";
$z[9]=Array("channelartlist","\n		<div data-am-widget=\"list_news\" class=\"am-list-news am-list-news-default\">\n			<!--列表标题-->\n			<div class=\"am-list-news-hd am-cf\">\n				<!--带更多链接-->\n				<a href=\"list.php?tid={dede:field name='id'/}\">\n					 <h2>{dede:field name='typename'/}</h2>\n				</a>\n			</div>\n			<div class=\"am-list-news-bd\">\n				<ul class=\"am-list\">{dede:arclist titlelen='60' row='8'}\n					<li class=\"am-g\"> <a href=\"view.php?aid=[field:id/]\" class=\"am-list-item-hd\">[field:title /]</a>\n					</li>{/dede:arclist}</ul>\n			</div>\n			<!--更多在底部-->\n			<div class=\"am-list-news-ft\"> <a class=\"am-list-news-more am-btn am-btn-default\" href=\"list.php?tid={dede:field name='id'/}\">查看更多 &raquo;</a>\n			</div>\n		</div>",2990,3750);
$z[10]=Array("include","",3750,3789);
$z[10][4]['filename']="footer_m.htm";

?>