<?php
$z[0]=Array("global","",171,194);
$z[0][4]['name']="cfg_chat";
$z[1]=Array("global","",293,320);
$z[1][4]['name']="cfg_basehost";
$z[2]=Array("global","",459,491);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("global","",609,636);
$z[3][4]['name']="cfg_basehost";
$z[4]=Array("channel","\n      	<div class=\"header__nav-item\"><a href='[field:typeurl/]' [field:rel/]>[field:typename/]</a></div>\n      	",663,932);
$z[4][4]['type']="son";
$z[4][4]['typeid']="1";
$z[4][4]['row']="10";
$z[4][4]['currentstyle']="<div class='header__nav-item on'><a href='~typelink~' ~rel~>~typename~</a></div>";

?>