<?php
$z[0]=Array("global","",78,101);
$z[0][4]['name']="cfg_chat";
$z[1]=Array("global","",124,151);
$z[1][4]['name']="cfg_info_tel";
$z[2]=Array("global","",174,201);
$z[2][4]['name']="cfg_info_fat";
$z[3]=Array("global","",224,253);
$z[3][4]['name']="cfg_info_phone";
$z[4]=Array("global","",281,309);
$z[4][4]['name']="cfg_info_mail";
$z[5]=Array("global","",332,363);
$z[5][4]['name']="cfg_info_address";

?>