<?php
$z[0]=Array("global","",74,102);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("wintitle","",112,128);
$z[2]=Array("global","",182,216);
$z[2][4]['name']="cfg_plus_dir";
$z[3]=Array("global","",258,292);
$z[3][4]['name']="cfg_plus_dir";
$z[4]=Array("global","",507,541);
$z[4][4]['name']="cfg_plus_dir";
$z[5]=Array("wecome_info","",570,589);
$z[6]=Array("winform","",694,709);
$z[7]=Array("lang_cms_powerby","",756,780);

?>